// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'orderDetail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_OrderDetail _$$_OrderDetailFromJson(Map<String, dynamic> json) =>
    _$_OrderDetail(
      json['id'] as int?,
      json['order_code'] as String?,
      json['user_id'] as String?,
      json['user_type'] as String?,
      json['order_date'] as String?,
      json['confirm_status'] as String?,
      json['order_status'] as String?,
      json['order_note'] as String?,
      json['delimen_id'] as String?,
      json['created_at'] as String?,
      json['updated_at'] as String?,
      json['delimen_note'] as String?,
      json['staff_note'] as String?,
      json['oid'] as String?,
      json['order_create_date'] as String?,
      json['order_id'] as String?,
      json['from_name'] as String?,
      json['from_phone'] as String?,
      json['from_addres'] as String?,
      json['from_township'] as String?,
      json['from_state'] as String?,
      json['item_info'] as String?,
      json['number_of_item'] as String?,
      json['width'] as String?,
      json['height'] as String?,
      json['length'] as String?,
      json['weight'] as String?,
      json['can_pickup_date'] as String?,
      json['pay_status'] as String?,
      json['photo_1'] as String?,
      json['remark'] as String?,
      json['to_name'] as String?,
      json['to_phone'] as String?,
      json['to_address'] as String?,
      json['to_township'] as String?,
      json['to_state'] as String?,
      json['puckup_fee'] as String?,
      json['deli_fee'] as String?,
      json['service_total'] as String?,
      json['item_amount'] as String?,
      json['net_total'] as String?,
      json['payment_method'] as String?,
      json['system_note'] as String?,
      json['request_date'] as String?,
      json['esign'] as String?,
      json['o_status'] as String?,
    );

Map<String, dynamic> _$$_OrderDetailToJson(_$_OrderDetail instance) =>
    <String, dynamic>{
      'id': instance.id,
      'order_code': instance.order_code,
      'user_id': instance.user_id,
      'user_type': instance.user_type,
      'order_date': instance.order_date,
      'confirm_status': instance.confirm_status,
      'order_status': instance.order_status,
      'order_note': instance.order_note,
      'delimen_id': instance.delimen_id,
      'created_at': instance.created_at,
      'updated_at': instance.updated_at,
      'delimen_note': instance.delimen_note,
      'staff_note': instance.staff_note,
      'oid': instance.oid,
      'order_create_date': instance.order_create_date,
      'order_id': instance.order_id,
      'from_name': instance.from_name,
      'from_phone': instance.from_phone,
      'from_addres': instance.from_addres,
      'from_township': instance.from_township,
      'from_state': instance.from_state,
      'item_info': instance.item_info,
      'number_of_item': instance.number_of_item,
      'width': instance.width,
      'height': instance.height,
      'length': instance.length,
      'weight': instance.weight,
      'can_pickup_date': instance.can_pickup_date,
      'pay_status': instance.pay_status,
      'photo_1': instance.photo_1,
      'remark': instance.remark,
      'to_name': instance.to_name,
      'to_phone': instance.to_phone,
      'to_address': instance.to_address,
      'to_township': instance.to_township,
      'to_state': instance.to_state,
      'puckup_fee': instance.puckup_fee,
      'deli_fee': instance.deli_fee,
      'service_total': instance.service_total,
      'item_amount': instance.item_amount,
      'net_total': instance.net_total,
      'payment_method': instance.payment_method,
      'system_note': instance.system_note,
      'request_date': instance.request_date,
      'esign': instance.esign,
      'o_status': instance.o_status,
    };
